# This file was auto-generated by Fern from our API Definition.

from .video_feed_for_camera_video_camera_id_get_request_camera_id import (
    VideoFeedForCameraVideoCameraIdGetRequestCameraId,
)

__all__ = ["VideoFeedForCameraVideoCameraIdGetRequestCameraId"]
