# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing
import pydantic


class AdminSettingsResponse(UniversalBaseModel):
    """
    Contains the settings returned in the admin page
    """

    dataset_name: str
    episode_format: str
    freq: int
    remote_server_inference_port: int
    remote_server_inference_url: str
    task_instruction: str
    video_codec: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
