# This file was auto-generated by Fern from our API Definition.

import typing

AdminSettingsResponseVideoCodec = typing.Union[
    typing.Literal["avc1", "hev1", "mp4v", "hvc1", "avc3", "av01", "vp09"], typing.Any
]
