# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class JointsReadResponse(UniversalBaseModel):
    """
    Response to read the joints of the robot.
    """

    angles_motor_units: typing.List[int] = pydantic.Field()
    """
    A list of length 7, with the position of each joint in motor units.
    """

    angles_rad: typing.List[float] = pydantic.Field()
    """
    A list of length 7, with the position of each joint in radian.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(
            extra="allow", frozen=True
        )  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
