# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class RecordingStopResponse(UniversalBaseModel):
    """
    Response when the recording is stopped. The episode is saved in the given path.
    """

    episode_folder_path: typing.Optional[str] = pydantic.Field(default=None)
    """
    Path to the folder where the episode is saved.
    """

    episode_index: typing.Optional[int] = pydantic.Field(default=None)
    """
    Index of the recorded episode in the dataset.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
