# This file was auto-generated by Fern from our API Definition.

import typing

SingleCameraStatusCameraType = typing.Union[
    typing.Literal[
        "classic", "stereo", "realsense", "dummy", "dummy_stereo", "unknown"
    ],
    typing.Any,
]
